export default [
  { firstName: 'Boy',
    lastName: 'Test',
    parent1: 2,
    parent2: 1,
    id: 5,
    special: '1234567'},
  { firstName: 'Girl',
    lastName: 'Test',
    parent1: 2,
    parent2: 1,
    id: 4,
    special: '7654321'},
  { firstName: 'Kid',
    lastName: 'Test',
    parent1: 1,
    parent2: 2,
    id: 6,
    special: '5675679'},
  { firstName: 'Mom',
    lastName: 'Test',
    parent1: '',
    parent2: '',
    id: 1,
    special: '1234567'},
  { firstName: 'Dad',
    lastName: 'Lette',
    id: 2,
    special: '1234567'},
  { firstName: 'Rando',
    lastName: 'Burando',
    id: 3,
    special: '1234567'}
]
